import { StyleSheet } from 'react-native'
import { colors, radius } from '../theme'

export const styles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.cream },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cream },
  content: { padding: 16, paddingBottom: 32 },
  screenTitle: { fontSize: 20, fontWeight: '700', color: colors.g800 },
  screenSub: { fontSize: 13, color: colors.muted, marginTop: 2, marginBottom: 16 },
  cardTitle: { fontSize: 15, fontWeight: '700', color: colors.g800, marginBottom: 10 },
  pendingRow: { borderTopWidth: 1, borderTopColor: colors.cream, paddingVertical: 10, gap: 8 },
  pendingName: { fontSize: 13.5, fontWeight: '700', color: colors.g800 },
  pendingDetail: { fontSize: 12, color: colors.muted, marginTop: 1 },
  pendingActions: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
  pendingAppRow: { gap: 8, backgroundColor: colors.cream, borderRadius: radius.md, padding: 8 },
  pendingAppText: { fontSize: 11.5, color: colors.text },
  pendingSignature: { width: 70, height: 40, backgroundColor: colors.white, borderRadius: 4, borderWidth: 1, borderColor: colors.warmBorder },
  pendingThumbLabel: { fontSize: 9.5, color: colors.muted, marginTop: 2 },
  approveBtn: { fontSize: 12.5, fontWeight: '700', color: colors.white, backgroundColor: colors.g700, paddingVertical: 6, paddingHorizontal: 12, borderRadius: radius.md, overflow: 'hidden' },
  denyBtn: { fontSize: 12.5, fontWeight: '700', color: colors.danger, borderWidth: 1, borderColor: colors.dangerBorder, paddingVertical: 5, paddingHorizontal: 12, borderRadius: radius.md, overflow: 'hidden' },
  tabRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  tabBtn: { flex: 1, textAlign: 'center', fontSize: 13, fontWeight: '700', color: colors.muted, paddingVertical: 9, borderRadius: radius.md, borderWidth: 1, borderColor: colors.warmBorder, backgroundColor: colors.white, overflow: 'hidden' },
  tabBtnActive: { color: colors.white, backgroundColor: colors.g700, borderColor: colors.g700 },
  search: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.warmBorder, borderRadius: radius.md, paddingVertical: 10, paddingHorizontal: 14, fontSize: 14, marginBottom: 10 },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  filterChip: { fontSize: 12.5, fontWeight: '600', color: colors.text, paddingVertical: 6, paddingHorizontal: 12, borderRadius: 99, borderWidth: 1, borderColor: colors.warmBorder, backgroundColor: colors.white, overflow: 'hidden' },
  filterChipActive: { borderColor: colors.g700, backgroundColor: colors.g50, color: colors.g700, fontWeight: '700' },
  memberCard: { backgroundColor: colors.white, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.warmBorder, padding: 14, marginBottom: 10 },
  memberName: { fontSize: 15, fontWeight: '700', color: colors.g800, marginBottom: 4 },
  guardianLine: { fontSize: 11.5, color: colors.muted, marginBottom: 6 },
  memberChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
  emptyText: { textAlign: 'center', color: colors.muted, fontStyle: 'italic', paddingVertical: 40 },
  adminHint: { fontSize: 11.5, color: colors.muted, fontStyle: 'italic', marginTop: 10 },
})
